title: Caleb Vredevoogd
description: Hello, this is my blog. This is where I will post about projects of mine. I also plan on writing reviews as well for books, movies, etc.
theme: jekyll-theme-minimal
plugins:
  - jekyll-menus
  - jekyll-feed
