title: Caleb Vredevoogd
description: Hello, my name is Caleb Vredevoogd. I'm a software developer and currently a Computer Science student. This is a portfolio where you can find posts about projects as well as my resume.
theme: jekyll-theme-minimal
plugins:
  - jekyll-menus
  - jekyll-feed
collections:
  projects:
    output: true
    permalink: /projects/:path/
